apiVersion: v1
kind: ReplicationController
metadata:
 name: fio
spec:
 replicas: 2
 selector:
  name: fio
 template:
  metadata:
   labels:
    name: fio
  spec:
   containers:
    - name: fio
      image: saye16/fio
   terminationGracePeriodSeconds: 1200
